config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :cat_rental_requests, only: [:index]
  end

  resources :cat_rental_requests, only: [:show, :new, :edit, :create, :update, :destroy]

  patch '/cat_rental_request/:id/approve', to: 'cat_rental_requests#approve', as: 'approve'
    patch '/cat_rental_request/:id/deny', to: 'cat_rental_requests#deny', as: 'deny'
  root to: 'cats#index'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS  =[
    "black",
    "orange",
    "tabby",
    "pink"
  ]

  validates :birth_date, :name, :color, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color"}

  validates :sex, length: { maximum: 1 }, inclusion: { in: ["M", "F"],
    message: "That's not a sex! Silly billy."}


  has_many :cat_rental_requests, dependent: :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: ["PENDING", "APPROVED", "DENIED"]}

  validate :cannot_have_overlapping_approved_requests

  belongs_to :cat

  def overlapping_requests
    CatRentalRequest.where(cat_id: cat_id).where.not(id: id)
    .where("(start_date BETWEEN :starting_date AND :ending_date) OR (end_date BETWEEN :starting_date AND :ending_date)",
      starting_date: start_date, ending_date: end_date)

  end

  def overlapping_approved_requests
    if status == "APPROVED"
      overlapping_requests.where(status: "APPROVED")
    else
      []
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def approve!
    transaction do
      self.status = "APPROVED"
      save!
      overlapping_pending_requests.each do |non_important_request|
        non_important_request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    save!
  end

  private

  def cannot_have_overlapping_approved_requests
    if overlapping_approved_requests.count > 0
      errors[:overlapping_approved_requests] << "Can't have overlapping approved requests!"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cat = Cat.find(params[:cat_id])
    @cat_rentals = @cat.cat_rental_requests.order(:start_date)
    render :index
  end

  # def show
  #   @cat_rental = CatRentalRequest.find(params[:id])
  #   render :show
  # end

  def new
    @cat_rental = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @cat_rental = CatRentalRequest.new(rental_params)
    @cats = Cat.all
    if @cat_rental.save!
      redirect_to cat_cat_rental_requests_url(@cat_rental)
    else
      render :new
    end
  end

  def edit
    @cat_rental = CatRentalRequest.find(params[:id])
    @cats = Cat.all
    render :edit
  end

  def update
    @cat_rental = CatRentalRequest.find(params[:id])
    @cat_rental.update(rental_params)
    redirect_to cat_url(@cat_rental)
  end

  def approve
    @cat_rental = CatRentalRequest.find(params[:id])
    @cat_rental.approve!
    redirect_to cat_url(@cat_rental)
  end

  def deny
    @cat_rental = CatRentalRequest.find(params[:id])
    @cat_rental.deny!
    redirect_to cat_url(@cat_rental)
  end

  private
  def rental_params
    params.require(:rental).permit(
      :cat_id, :start_date, :end_date
    )
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    @cat_rentals = @cat.cat_rental_requests.order(:start_date)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    redirect_to cat_url(@cat)
  end

  private
  def cat_params
    params.require(:cat).permit(
      :birth_date, :color, :name, :sex, :name, :description
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% method_request = @cat_rental.persisted? ? "patch" : "post" %>
<% submit = @cat_rental.persisted? ? "Update appointment" : "Create appointment" %>
<% action_url = @cat_rental.persisted? ? cat_rental_request_url(@cat_rental) : cat_rental_requests_url %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= method_request %>"
  <label for="rental[cat_id]" >Choose a cat</label>
  <select name="rental[cat_id]">
    <option> </option>
    <% @cats.each do |cat| %>
      <option  value="<%= cat.id %>"
            <%= "selected" if @cat_rental.cat_id = cat.id %>>
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br />

  <label for="rental[start_date]">Start Date</label>
  <input type="date" name="rental[start_date]" value="<%= @cat_rental.start_date %>"/>
  <br />

  <label for="rental[end_date]">End Date</label>
  <input type="date" name="rental[end_date]"value="<%= @cat_rental.end_date %>"/>
  <br />

  <input type="submit" value="<%= submit %>" />
</form>

app/views/cat_rental_requests/edit.html.erb
<h1>Update Request</h1>


<%= render "form" %>

app/views/cat_rental_requests/index.html.erb
<h1><%= @cat.name %></h1>


<table  border="1">
  <tr>
    <th> Start Date </th>
    <th> End Date </th>
    <th> Status </th>
  </tr>

  <% @cat_rentals.each do |rental| %>
    <tr>
      <td><%= rental.start_date %></td>
      <td><%= rental.end_date %></td>
      <td><%= rental.status %></td>
      <td>
        <%= link_to "Update Request", cat_rental_requests_url(rental) %>
      </td>
    </tr>
    <% end %>
</table>

app/views/cat_rental_requests/new.html.erb
<h1>Request a Rental</h1>

<%= render "form" %>

app/views/cats/_cat_appointments.html.erb
<table  border="1">
  <tr>
    <th> Start Date </th>
    <th> End Date </th>
    <th> Status </th>
  </tr>

  <% @cat_rentals.each do |rental| %>
    <tr>
      <td><%= rental.start_date %></td>
      <td><%= rental.end_date %></td>
      <td><%= rental.status %></td>
      <td>
        <%= link_to "Update Request", edit_cat_rental_request_url(rental) %>
      </td>
      <td>
        <%= button_to "Approve", approve_url(rental), method: "patch" %>
      </td>
      <td>
        <%= button_to "Deny", deny_url(rental),  method: "patch" %> 
      </td>
    </tr>
    <% end %>
</table>

app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url  %>
<% form_method = @cat.persisted? ? "PATCH" : "POST"  %>
<% submit_text = @cat.persisted? ? "Update Cat!" : "Create Cat!"  %>

<form action= "<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <label for="cat[name]">Name</label>
  <input type="text" name="cat[name]" value="<%=@cat.name %>">
  <br/>

  <label for="cat[birth_date]">Birthday</label>
  <input type="date" name="cat[birth_date]" value="<%=@cat.birth_date %>">
  <br/>

  <label for="cat[color]">Color</label>
  <select name="cat[color]">
    <option> </option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>"
              <%= "selected" if @cat.color == color %>>
        <%= color %>
      </option>
    <% end %>
  </select>
  <br/>

  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
                <%= "checked" if @cat.sex == "F" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
                <%= "checked" if @cat.sex == "M" %>>
  <label for="cat_sex_male">Male</label>
  <br />

  <label for="cat[description]">Description</label>
  <br />
  <textarea name="cat[description]"><%= @cat.description %></textarea>
  <br />

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %></h1>

<%= render "form" %>

app/views/cats/index.html.erb
<h1>All cats</h1>

<% @cats.each do |cat| %>
  <p><%= link_to cat.name, cat_url(cat) %></p>
<% end %>

app/views/cats/new.html.erb
<h1>Create A New CAT!</h1>

<%= render "form" %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table  border="1">
  <tr>
    <th> Name </th>
    <th> Birth Date </th>
    <th> Color </th>
    <th> Sex </th>
    <th> Description </th>
  </tr>

  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<h4>Appointments</h4>


<%= render "cat_appointments" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>